name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Greetings! Thank you for making your first Issue on the OpenControl Project!'' first issue'
        pr-message: 'Greetings! Thank you for making your first Pull Request on the OpenControl Project!'' first pr'
